language: java
sudo: false

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

matrix:
  include:
    - python: 3.6
      install: pip install flake8
      script: flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics

script:
- sh -c 'cd grobid-ner && mvn clean install -Dmaven.test.skip=true'

#after_success:
#  - mvn clean cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin:report
