language: java
sudo: false

addons:
  apt:
    packages:
      - oracle-java8-installer
      - oracle-java9-installer
      - oracle-java10-installer

matrix:
  include:
    - jdk: oraclejdk8
    - jdk: oraclejdk9
    - jdk: oraclejdk10
    - language: python
      python: 3.6
      install: pip install flake8
      script: flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics

script:
- sh -c 'cd grobid-ner && mvn clean install -Dmaven.test.skip=true'

#after_success:
#  - mvn clean cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin:report
